NP-41615-findable-doi-as-api-gateway, work in progress
BIBSYSDEV/nva-doi-registrar-client pull request #125
Opened 2023-03-23 11:47 UTC by truhacevkir

2023-03-23 12:04 UTC, anetteOlli requested changes

2023-03-23 12:04 UTC, anetteOlli commented on datacite-findable-doi-handler/src/main/java/no/unit/nva/datacite/handlers/FindableDoiHandler.java
> +        var doi = Doi.fromUri(input.getDoi());
Hvis Doi ikke finnes fra før av så må vi skaffe en draft først.

2023-03-23 13:36 UTC, truhacevkir commented on template.yaml
> +      Events:
done

2023-03-24 12:01 UTC, anetteOlli requested changes

2023-03-24 12:21 UTC, truhacevkir commented on docs/openapi.yaml
> +                $ref: '#/components/schemas/Doi'
er nå lagt til

2023-03-24 12:21 UTC, truhacevkir commented on docs/openapi.yaml
> +        responses: { }
inputen blir validert inn i koden

2023-03-24 13:06 UTC, anetteOlli requested changes

2023-03-24 13:06 UTC, anetteOlli commented on docs/openapi.yaml
> +        - publicationId
Tror ikke denne måten er godkjent av open api.
Dobbelt sjekk med å sette custom branch på sandbox.
Og forsøk en post request uten publicationId og customerId

2023-03-24 13:06 UTC, anetteOlli commented on docs/openapi.yaml
> +        - publicationId
Du får svar innen 10ms så er det apigateway som har fisket valideringa. Får du svar etter +300ms så er det lambda valideringa som har skjedd.

2023-03-24 14:48 UTC, merged