Np 1968 delete draft doi handler
BIBSYSDEV/nva-doi-registrar-client pull request #45
Opened 2021-01-08 11:51 UTC by janbj

2021-01-08 12:13 UTC, brinxmat approved these changes

2021-01-08 13:22 UTC, axthosarouris requested changes
Requested changes:
Remove env variables that are not in use.
Test that shows what happens when the remote server (datacite) returns a failure.

Suggested changes (but not required):
Delete the specialized environment class.

2021-01-08 13:22 UTC, axthosarouris commented on datacite-delete-draft-doi-handler/src/main/java/no/unit/nva/datacite/handlers/DeleteDraftDoiAppEnv.java
> +public final class DeleteDraftDoiAppEnv {
All these methods  are used only in one handler? Why to have a separate class? each class we create is some extra time in the cold start

2021-01-08 13:22 UTC, axthosarouris commented on datacite-delete-draft-doi-handler/src/main/java/no/unit/nva/datacite/handlers/DeleteDraftDoiAppEnv.java
> +    public static final String DATACITE_CONFIG = "DATACITE_CONFIG";
The two first env variables are not used.

2021-01-08 13:22 UTC, axthosarouris commented on datacite-delete-draft-doi-handler/src/test/java/no/unit/nva/datacite/handlers/DeleteDraftDoiHandlerTest.java
> +public class DeleteDraftDoiHandlerTest {
what happens when deleting the draft doi fails?

2021-01-11 10:55 UTC, brinxmat approved these changes

2021-01-11 12:59 UTC, axthosarouris approved these changes

2021-01-11 14:07 UTC, merged